/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "matrix_algebra-test.check" instead.
 */

#include <check.h>

#line 1 "matrix_algebra-test.check"
#include "matrix_algebra.h"
#include "user_interface.h"

START_TEST(add_matrices_test)
{
#line 5
	double** test_matrix_A;
	double** test_matrix_B;
	double** test_matrix_C;

	malloc_matrix(&test_matrix_A);
	malloc_matrix(&test_matrix_B);
	malloc_matrix(&test_matrix_C);

	int x, y;

	for (y = 0; y < 2; y++)
	{
		for (x = 0; x < 2; x++)
		{
			test_matrix_A[y][x] = 1;
			test_matrix_B[y][x] = 2;
		}
	}

	add_matrices(test_matrix_A, test_matrix_B, test_matrix_C);

	
	fail_unless(test_matrix_C[0][0] == 3, "add function borked");
	
	free_matrix_space(test_matrix_A);
	free_matrix_space(test_matrix_B);
	free_matrix_space(test_matrix_C);
}
END_TEST

int main(void)
{
    Suite *s1 = suite_create("Core");
    TCase *tc1_1 = tcase_create("Core");
    SRunner *sr = srunner_create(s1);
    int nf;

    suite_add_tcase(s1, tc1_1);
    tcase_add_test(tc1_1, add_matrices_test);

    srunner_run_all(sr, CK_ENV);
    nf = srunner_ntests_failed(sr);
    srunner_free(sr);

    return nf == 0 ? 0 : 1;
}
